openapi: 3.0.3
info:
  title: Demo Client Management Api
  description: Client Service demonstration.
  contact:
    name: Demo
  license:
    name: private
  version: "1"
servers:
  - url: https://localhost:8081/api-docs
    variables:
      basePath:
        default: client
tags:
  - name: Client Management API
    description: Client Api Controller
paths:
  /client/updatePassword:
    put:
      tags:
        - Client Management API
      summary: Update Client Password
      description: API updates client password
      operationId: updatePassword
      requestBody:
        description: client
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
        required: true
      responses:
        200:
          description: Password updated successfully.
          content:
            application/json:
              schema:
                type: string
        400:
          description: Request Invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        401:
          description: Authentication has failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        403:
          description: The request is forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        409:
          description: Request syntax is correct, but request data was unable to satisfy
            validation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        422:
          description: Request syntax is correct, but request data was unable to satisfy
            validation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaveClientResponse'
        500:
          description: Unexpected server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-codegen-request-body-name: client
components:
  schemas:
    Client:
      title: Client
      required:
        - email
        - old_password
        - new_password
        - confirm_new_password
      type: object
      properties:
        email:
          maxLength: 70
          type: string
          pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$
          description: 'Client''s email. [Constraint: `client_email`]'
          example: user1@abc.com
        old_password:
          minLength: 10
          maxLength: 20
          type: string
          format: password
          description: 'Client''s old password. [Constraint: `old_password`]'
        new_password:
          minLength: 10
          maxLength: 20
          type: string
          format: password
          description: 'Client''s new password. [Constraint: `new_password`]'
        confirm_new_password:
          minLength: 10
          maxLength: 20
          type: string
          format: password
          description: 'Client''s new password. [Constraint: `confirm_new_password`]'
    ErrorResponse:
      title: ErrorResponse
      type: object
      properties:
        error_code:
          type: integer
          description: Error Code returned. Possible Values are HTTP Status Codes
          format: int32
        message:
          type: string
          description: Message describing the error that occurred. This message, along
            with the HTTP code, should always provide enough description to consumers
            about what has gone wrong.
          example: Unauthorised access to API.
        trace_id:
          type: string
          description: Trace Id for the exception scenario based on Zipkin Brave tracing
          example: 281bcfd8cf392377
    SaveClientResponse:
      title: SaveClientResponse
      type: object
      properties:
        errors:
          type: array
          description: List of validation errors.
          uniqueItems: true
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
        - code
      type: object
      properties:
        category:
          type: string
          description: Category is optional
          example: validation_failed
        code:
          type: string
          description: Code representing the validation rule that failed
          example: IN123
        description:
          type: string
          description: Description of the validation error
          example: Name cannot be blank
        field:
          type: string
          description: The name of the input field that triggered a validation error
          example: firstName
        rule_id:
          type: string
          description: Rule Id is optionally
          example: Rule001
        rule_name:
          type: string
          description: Rule Name is optionally
          example: Storage Type
        severity:
          type: string
          description: 'Severity: error or warning'
          example: error
    ValidationErrorResponse:
      title: ValidationErrorResponse
      type: object
      properties:
        errors:
          type: array
          description: List of validation errors.
          uniqueItems: true
          items:
            $ref: '#/components/schemas/ValidationError'